site_name: 'GAIA AIR Documentation'
theme: 'readthedocs'
nav:
  - 'Home': 'index.md'
  - 'Planificación y Gestión': 'docs/planificacion_gestion.md'
  - 'Requisitos del Sistema': 'docs/requisitos_sistema.md'
  - 'Arquitectura del Sistema': 'docs/arquitectura_sistema.md'
  - 'Diseño Detallado': 'docs/diseño_detallado.md'
  - 'Desarrollo y Validación': 'docs/desarrollo_validacion.md'
  - 'Simulación y Pruebas': 'docs/simulacion_pruebas.md'
  - 'Métricas de Desempeño': 'docs/metricas_desempeno.md'
  - 'Gestión de Configuración': 'docs/gestion_configuracion.md'
  - 'Cumplimiento Normativo': 'docs/cumplimiento_seguridad.md'
  - 'Documentación de Usuario': 'docs/documentacion_usuarios.md'
  - 'Cierre del Proyecto': 'docs/cierre_proyecto.md'
  - 'Recursos Complementarios': 'docs/recursos_complementarios.md'
  - 'Plan de Obtención de Datos': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-004-A.md'
  - 'Visualizaciones y Gráficos': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-005-A.md'
  - 'Roadmap Estratégico Detallado': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-006-A.md'
  - 'Propuesta de Valor: Ejemplos Concretos': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-007-A.md'
  - 'Gestión Documental y Trazabilidad': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-008-A.md'
  - 'Próximos Pasos': 'docs/GPAM/ATA05/GPAM-AMPEL-0201-05-009-A.md'
  - 'GAIA AIR ATA Index': 'GAIA_AIR_ATA_Index.md'
  - 'Glossary': 'Glossary'
